# backendStore -- Either a filepath, a database or the default value. At present, postgres is the only database engine supported by the official image. Should you want to connect to any other database, please refer to the README.
backendStore:
  # backendStore.filepath -- A local or remote filesystem path (e.g. /mnt/persistent-disk)
  filepath:

  # backendStore.postgres -- A map with the values for (username, password, host, port and database).
  #postgres:
  #   username:
  #   password:
  #   host:
  #   port:
  #   database:

  mysql:
     username: root
     password: mysql123 # pragma: allowlist secret
     host: mysql.mlflow.svc.cluster.local
     port: 3306
     database: mlflow

awsAccessKeyId: minio
awsSecretAccessKey: minio123 # pragma: allowlist secret
s3EndpointUrl: http://minio.mlflow.svc.cluster.local:9000

# defaultArtifactRoot -- A local or remote filepath (e.g. s3://my-bucket). It is mandatory when specifying a database backend store
defaultArtifactRoot: s3://mlflow-artifacts/
