{{- if .Values.backendStore.mysql -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.mysqlSecretName" . }}
type: Opaque
data:
  password: {{ required "you must specify a mysql password" .Values.backendStore.mysql.password | b64enc }}
{{- end }}
